version: '3.8'

services:
  api_gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile.prod
      target: ${STAGE:-testing}
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
    environment:
      PORT: 3000 
      JWT_KEY: secret_key_test 
