version: '3.8'

services:
  api_gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile.prod
      target: ${STAGE:-testing}
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
    environment:
      PORT: 3000 
      JWT_KEY: secret_key_test 
  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.prod
      target: ${STAGE:-testing}
    volumes:
      - ./user-service:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
    expose:
      - 8080
    ports:
      - "8080:8080/tcp"
    environment:
      PORT: 8080 
    depends_on:
      - postgres
  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=user_db
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
volumes:
  postgresql_data:
    driver: local